### ISSUE TITLE
Sink error result to metricsServer not working

### ISSUE THREAD

**Issue by dzy176** [alibaba/kubeskoop#263]
https://github.com/alibaba/kubeskoop/blob/2e79815afe27463313ca73f44e789ea97414cc19/pkg/exporter/cmd/server.go#L299C1-L314C1

In our case, we use serveral sinks config, like:
```yaml
...
      sinks:
      - name: kafka
        args:
          addr: ...
          topic: ...
      - name: elasticsearch
        args:
          addr: ...
          index: ...
```

if something wrong with kafka, when we start exporter, the whole metricServer will stop. 

![12607B89-CB90-44FE-A92F-A94EF214C3DF](https://github.com/alibaba/kubeskoop/assets/25903305/ce1cea90-aa51-4489-8260-af1ea1fa0725)

I think it's better to record the err log instead of return. Because the second sink we used is valid, we hope events push to elasticsearch.
```go
		//sink
		sinks, err := createSink(cfg.EventConfig.EventSinks)
		if err != nil {
			log.Errorf("failed create sinks, err: %v", err)
			return
		}
```
