### ISSUE TITLE
Open file descriptor leak in qdisc?

### ISSUE THREAD

**Issue by dreamerlzl** [alibaba/kubeskoop#285]
# Environment
kubeskoop version: v0.1.1
configuration:
```yaml
port: 9102
sinks:
  - name: stderr
enable_controller: false
metrics:
  probes:
  - name: qdisc
```

# What happened?

The number of open file descriptors by kubeskoop's container `inspector` keeps increasing until reaching the node limit.

![1916C563-11AE-4D98-8938-D5981CB4AB46](https://github.com/alibaba/kubeskoop/assets/28644777/074124cb-bb13-4461-9bc7-1c552b8a1fef)

here in the picture, there are 6 namespaces in the k8s cluster. The number of open fd increases periodically.

# What is expected to happen?

The count of open file descriptor by kubeskoop doesn't grow infinitely, or
the maximum of open file descriptors allowed for kubeskoop is configurable or have a reasonable default value during launch.

# How to reproduce

Run kubeskoop in any real k8s cluster where the nodes are bare metals.
