### ISSUE TITLE
Some problems with Diagnosis

### ISSUE THREAD

**Issue by Robin3Chan** [alibaba/kubeskoop#313]
1. Capture:
When Capturing in pods like kubeskoop's  "pod controller" , meet this error: "failed to run command: pod not found on nettop cache".
When Capturing in pods like kubeskoop's  "pod agent", it meet this error: "failed to upload task result", and "pod controller" seems to crash and reload.

2. Connectivity Diagnosis:
How could I submit args like "--network-plugin", when auto-detection failed on web console?

**Comment by Lyt99** [comment]
Hi, thanks for reporting this issue!

1. Seems like the controller is not working properly. Could you please provide the error log of controller?

2. You can use `diagnose.extraArgs` in controller config to  pass custom arguments to the diagnose. The controller config is in a ConfigMap named `controller-config` or `kubeskoop-controller-config` 

For example:
```yaml
logLevel: debug
server:
  httpPort: 10264
  agentPort: 10263
controller:
  namespace: kubeskoop
  prometheus: ""
  loki: ""
  database:
    type: sqlite3
  diagnose:
    # Set network plugin to flannel.
    extraArgs:
      - --network-plugin=flannel
```
